### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by jbwilkes** [LukasErekson/pyrisk#13] opened 2020-10-14 00:59 UTC
I cloned the repo right before running this so the errors are based upon the most recent code

[jbwilkes@byu.local@acme39 pyrisk]$ python pyrisk.py -p=2 -g=10 SD_StupidAI ChronAI --nocurses --deal
Starting process 1 with 5 games
Starting process 2 with 5 games
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Process Process-2:
  File "/usr/local/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "pyrisk.py", line 61, in launch_in_process
    configure_logger(logger, args.log, pid,game=j+1)
  File "pyrisk.py", line 44, in configure_logger
    logger.handlers.pop()
IndexError: pop from empty list
Joined process 1
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "pyrisk.py", line 61, in launch_in_process
    configure_logger(logger, args.log, pid,game=j+1)
  File "pyrisk.py", line 44, in configure_logger
    logger.handlers.pop()
IndexError: pop from empty list
Joined process 2

**Comment by jbwilkes** [comment] 2020-10-14 01:07
I didn't get the same error when I leave out --nocurses, which I could see earlier Caleb commented in the other issue that he disabled it. So This might not actually be an issue

**Comment by lodeous** [comment] 2020-10-16 06:09
Do you still have this issue? The most recent code has the logger.handlers.pop() commented out. Lukas kindof changed how the logging was working but it seems like it works now.
I'm not getting the issue with the nocurses flag

**Comment by lodeous** [comment] 2020-10-16 06:50
I can't reproduce this. Can you update your code and if it works close the issue?

**Comment by lodeous** [comment] 2020-10-24 22:19
I'm assuming this is resolved

**Closed as completed by lodeous** 2020-10-24 22:19 UTC
